### ISSUE TITLE
database rewrite - meta + timeline

### ISSUE THREAD

**Issue by zelig** [ethersphere/swarm#1027]
# Storage refactor

## part I: DB refactor
part II is: https://github.com/ethersphere/go-ethereum/issues/1039

### Phase 0 - prerequisites

- [x] shed - field and index abstractions - https://github.com/ethersphere/go-ethereum/pull/993, https://github.com/ethereum/go-ethereum/pull/18183
- [x] ~~rushed~~
    - [x] multi mode accessors - https://github.com/ethersphere/go-ethereum/pull/1006
    - [x] ~~batch acceleration (if...?)~~ see 
    - [x] ~~iterators, subscription, continuous feeds~~https://github.com/ethersphere/go-ethereum/pull/1014

### Phase 1 - functionality

- [x] localstore package - merged as https://github.com/ethereum/go-ethereum/pull/19015
    - [x] dbstore using shed - #990 , #1022 
    - [x] define and test accessor modes 
    - [x] integrate mock global-store - https://github.com/ethersphere/go-ethereum/issues/992
- [x] iterators and subscriptions
    - [x] garbage collection - #1031
    - [x] push sync: syncer - db interface - #1030 
    - [x] pull sync: streamer - db interface

Context: [Garbage Collection and Syncing and Proof of Burn](https://hackmd.io/t-OQFK3mTsGfrpLCqDrdlw) - #1017 

### Phase 2 - integration

- [x] localstore integration - #1257 https://github.com/ethersphere/go-ethereum/pull/1282
    - [x] migrate old db to new https://github.com/ethersphere/go-ethereum/pull/1297
    - [x] netstore 
    - [x] hasherstore
    - [x] network package
    - [x] syncing simulation 
    - [x] syncing simulation with mock globalstore
    - [x] push syncer

---

### Phase 3 - optimisation

- [x] benchmarks 
    - [x] https://github.com/ethersphere/swarm/pull/1691
    - [x] https://github.com/ethersphere/swarm/pull/1681
    - [x] https://github.com/ethersphere/swarm/pull/1684
    - [x] https://github.com/ethersphere/swarm/pull/1686

**Comment by zelig** [comment]
@janos great job,  I consider this done :)
