### ISSUE TITLE
push syncing - meta + timeline

### ISSUE THREAD

**Issue by zelig** [ethersphere/swarm#1028]
# Syncing

## Push sync

https://hackmd.io/ffBjSu8RTyKikvRO7bYrzA#

### Phase 0 - prerequisite

- [x] pss handler refactor - https://github.com/ethersphere/go-ethereum/pull/965, https://github.com/ethereum/go-ethereum/pull/18169
- [x] kademlia health fix - https://github.com/ethersphere/go-ethereum/issues/994
- [x] snapshot loading fix - 
- [x] pss neighbpourhood addressing simulation - https://github.com/ethersphere/go-ethereum/pull/1016
- [x] pss forwarding fix - https://github.com/ethersphere/go-ethereum/issues/995, https://github.com/ethersphere/go-ethereum/pull/1008
- [x] push sync current implementation simulations pass - https://github.com/ethersphere/go-ethereum/pull/971

### Phase 1 - functionality

- [x] pusher 
     - https://github.com/ethersphere/go-ethereum/pull/1323
- [ ] tags/progress bar
    - [x] tags support in localstore 
    - [x] states and tags - progress bar backend - https://github.com/ethersphere/go-ethereum/issues/1019,   tags support in chunks  https://github.com/ethersphere/go-ethereum/pull/1341
    - [x] tags integration https://github.com/ethersphere/go-ethereum/pull/1347
    - [ ] POST API response - progress bar frontend - https://github.com/ethersphere/go-ethereum/issues/988
    - [x] tags (REST?) API 
    - [ ] persistence with state store

    
### Phase 2 - integration

- [x] with file store  
- [x] into swarm.go
- [x] with syncing strategy

### Phase 3 - optimisation

- [x] smoke test speed check
- [x] benchmark availabilities for various network and file sizes
- [x] measurements with and without push syncing

**Comment by zelig** [comment]
now over to https://github.com/ethersphere/swarm/pull/1392
