### ISSUE TITLE
Stability area meta + timeline

### ISSUE THREAD

**Issue by zelig** [ethersphere/swarm#1035]
# Tooling for network tests
## User-experience benchmarks and metrics

- [x] upload-download success rate - https://github.com/ethersphere/go-ethereum/issues/1033
- [x] upload speed for different file sizes #1091
  - [ ] hash response (split to chunks complete)
  - [ ] wait for local storage
- [x] download speed for different file sizes #1092
  - [ ] lowest latency
  - [ ] highest
  - [ ] average/median

### Need more work to define
- [ ] failure rate of accessing existing content long term
- [ ] availability delay for different file sizes
  - [ ] earliest node can retrieve
  - [ ] all nodes can retrieve

## Network testing

- [ ]    GlobalStore - shall we complete this, and add it as part of the Swarm app/deployment charts?
- [ ]     Chunk Explorer - shall we implement this tool - basically the ability to inspect chunks on given nodes?
- [ ]   Implement a tool to check if there is a path from one node to another based on syncing streams (server/client)?

### Simulation framework

- [ ] https://github.com/ethereum/go-ethereum/pull/18220
- [ ] https://github.com/ethersphere/go-ethereum/pull/1022
- [ ] remote (docker) adapters monitoring - https://github.com/ethersphere/go-ethereum/issues/991
- [ ] dropout models
- [ ] network contention models

### Mocking tools 
- [ ] reinstate mock db via global store 
- [ ] allow chunkless syncing -  https://github.com/ethersphere/go-ethereum/issues/992

## k8s 

- [x] Logging for k8s containers (maybe ELK / EFK - https://akomljen.com/get-kubernetes-logs-with-efk-stack-in-5-minutes/ ?)~
- [x] Container logs rotation  [PR#58](https://github.com/ethereum/swarm-cluster/pull/58)~
- [x] Ingress for services~
    - [x]  for developers to individual Swarm pods~
    - [x]  for developers to Logging and Monitoring and Kubernetes Dashboard~
    - [x]  for users to Swarm, load balanced across all Swarm pods~
    - [x]  for monitoring, logging, and other auxiliary services~
- [x] SSL for all ingress services~
- [x] Authentication/Authorization for developers (AWS IAM access/secret keys, with no access to AWS services or to AWS console) to~
    - [x] k8s / kubectl - it would be good if devs have access to this, so that they can port-forward and docker exec towards specific swarm containers.~
    - [x] Monitoring~
    - [x] Logging~
- [ ] Auto-scaling of staging cluster
- [ ] Documenting the setup
    - [x]  Terraform for the initial AWS EKS setup~
        - [x] Variables, such as different launch groups, and instance types, and why we need them~
    - [x] Kubernetes Dashboard~
    - [ ]  Prometheus Monitoring
    - [ ] Logging
    - [ ] Geth application and how to deploy a new version
    - [x] Swarm application and how to deploy a new version~
- [x] AWS Usage/Costs dashboard~
- [x]  Monitoring of PV EBS drives - the dashboards that come with the current Monitoring stack don't have this.~
- [ ] Hardening for:
    - [ ] Logging setup.
    - [ ] Metrics setup.
    - [ ] All Roles and Service Accounts created by external helm applications we use.
    - [ ] OS patching?
- [ ] Upgrade strategy for k8s

**Comment by petyaracz** [comment]
> upload speed for different file sizes

 what's the diff between `hash response` and `wait for local storage` ?

**Comment by zelig** [comment]
@petyaracz disk storage is asyncronous, it does not finish strictly by the time the chunker (and the API) returns the swarm hash.
