### ISSUE TITLE
kademlia, connectivity, stability   -- meta

### ISSUE THREAD

**Issue by zelig** [ethersphere/swarm#1068]
- [x] data races https://github.com/ethersphere/go-ethereum/issues/1102
- [x] kademlia/pot
    - [x] fix bug in PO calculation through https://github.com/ethersphere/go-ethereum/pull/1079
    - [x]  swarm/network: Revised depth and health for Kademlia #1051 https://github.com/ethersphere/go-ethereum/pull/1051
    - [x] swarm/network: Make MinProxBinSize constant across simulation https://github.com/ethersphere/go-ethereum/pull/1074
    - [x] ~~swarm/network: Add tests for complex connectivity evaluations https://github.com/ethersphere/go-ethereum/pull/1069 , https://github.com/ethersphere/go-ethereum/pull/1108~~
    - [x]  swarm/network: remove isproxbin bool from kad.Each* iterfunc #18239  https://github.com/ethereum/go-ethereum/pull/18239
    - [x] kademlia eachbin https://github.com/ethereum/go-ethereum/pull/18355 
         - [x] pull sync subscription tests https://github.com/ethersphere/go-ethereum/pull/1052
         - [x] rewrite pulls sync subscription creation not to use  kad.EachBin (and eliminate it) https://github.com/ethersphere/go-ethereum/issues/1071
   - [x] ~~swarm/network: Refactor peer suggestion engine + SuggestPeer unit tests #1088~~ ,  
   - [x] ~~RPC call to request subscription info https://github.com/ethereum/go-ethereum/pull/18284~~    
   - [x] Update peer suggestion engine after kademlia depth redefinition https://github.com/ethersphere/go-ethereum/issues/1063
        - [x] peer suggestion update https://github.com/ethereum/go-ethereum/pull/18404
        - [x] saturation check in kademlia health https://github.com/ethersphere/go-ethereum/issues/1195, ~https://github.com/ethersphere/go-ethereum/issues/1153~
        - [x] fix saturation check https://github.com/ethersphere/go-ethereum/issues/1263, https://github.com/ethereum/go-ethereum/pull/19155
   - [x] fix inconsistencies in pot iterators https://github.com/ethersphere/go-ethereum/issues/1053
       - [x] fix remove func https://github.com/ethereum/go-ethereum/pull/18431
       - [x] eliminate po arg from each/eachFrom iterator func https://github.com/ethersphere/go-ethereum/issues/1104, https://github.com/ethersphere/go-ethereum/issues/1114, https://github.com/ethereum/go-ethereum/pull/18452
      - [x] ~~ambiguity https://github.com/ethersphere/go-ethereum/issues/1103~~  backlog
      - [x] ~~comments https://github.com/ethersphere/go-ethereum/issues/1101~~ backlog
- [x] p2p/simulation
    - [x] p2p/simulation: Test snapshot correctness and minimal benchmark
 https://github.com/ethereum/go-ethereum/pull/18287
    - [x] p2p/simulation: move connection methods from swarm/network/simulation
https://github.com/ethereum/go-ethereum/pull/18305, https://github.com/ethereum/go-ethereum/pull/18323
    - [x] Part three will add a snapshot generation binary leveraging the different configurations provided by part two. https://github.com/ethersphere/go-ethereum/pull/1077
    - [x] ~~Part four will add exhaustive benchmarks with different snapshots generated from part three.~~ backlog??
    - [x] ~~[wip] Leaner swarm/network and p2p/simulations https://github.com/ethersphere/go-ethereum/pull/1076~~
    - [x] eliminate pivot https://github.com/ethereum/go-ethereum/pull/18426
    - [x] Rehabilitate WaitTillHealthy for correct kademlia depth https://github.com/ethersphere/go-ethereum/issues/994
    - [x] various fixes for longrunning simulations  https://github.com/ethereum/go-ethereum/pull/19208
- [x] pss forward https://github.com/ethersphere/go-ethereum/pull/1043
- [x] pss neighbourhood simulations https://github.com/ethersphere/go-ethereum/issues/987, https://github.com/ethersphere/go-ethereum/pull/1016 https://github.com/ethersphere/go-ethereum/issues/1284 https://github.com/ethereum/go-ethereum/pull/19278 
- [x] connectivity
    - [x] full connectivity issue (maxpeers) https://github.com/ethersphere/go-ethereum/issues/1094 
    - [x] swarm bootnode with hive protocol https://github.com/ethersphere/go-ethereum/issues/1111
   - [x] maxpeers https://github.com/ethersphere/go-ethereum/issues/864
   - [x]    BootNodes entry in config file not working as documented #1023    https://github.com/ethersphere/go-ethereum/issues/1023
   - [x]  ~~Swarm nodes don't find each other #1020  https://github.com/ethersphere/go-ethereum/issues/1020~~
   - [x] hive bug: needed shallow peers are not sent to nodes beyond connection's proximity order https://github.com/ethereum/go-ethereum/pull/19274 
   - [x]  Use actual remote peer ip in underlay https://github.com/ethersphere/go-ethereum/pull/1224
   - [x] new underlay updated on existing peers in address book https://github.com/ethersphere/go-ethereum/issues/1268
  -  [x]  reenable p2p/discovery and disable dynamic dialling https://github.com/ethereum/go-ethereum/pull/19189
  - [x] fix to faulty peers forwarding  https://github.com/ethereum/go-ethereum/pull/19274
- [ ] ENR https://github.com/ethersphere/go-ethereum/issues/1018 - https://github.com/ethersphere/go-ethereum/pull/1296
    - [ ] p2p trusted node in addpeer https://github.com/ethersphere/go-ethereum/issues/1082
    - [ ] transmit ENR in RLPx handshake - https://github.com/ethereum/go-ethereum/pull/19220
    - [x] Preliminary changes in swarm/network and embed ENR in simulation - Prerequities for ENR replacing handshake - https://github.com/ethereum/go-ethereum/pull/19275
    - [x]  Enable ENR in binary/execadapter https://github.com/ethersphere/go-ethereum/pull/1302
    - [ ]  Remove handshake from swarm/network
    - [ ]  Eliminate swarm/network:BzzAddr
    - [ ]  Merge swarm/network:BzzPeer and swarm/network:Peer
    - [ ] Remove handshake from p2p/protocols
    - [x] Move p2p/protocols to swarm package
