### ISSUE TITLE
Make and Keep Swarm's Code Race Free

### ISSUE THREAD

**Issue by frncmx** [ethersphere/swarm#1102]
Recently we found a data race in our code base and almost introduced a new one. We need an automated way to keep our code race free, but first we need to make it clean again.

**Tasks**
- [x] Identify data races currently present in our code and create tasks for fixing them
- [x] Fix all data races
- [x] Create a CI job which ensures the code remains data race free - #741 

**Data Races**
- [x] #1109 - fetcher_test.go
- [x] #1086 - swarm/network
- [x] #1110 - p2p/simulations - TestUpDownNodeIDs, TestStartStopNode, TestStartStopRandomNode, TestStartStopRandomNodes 
- [x] #1112 - kademlia - TestNetworkID
- [x] #1115 - protocol.go - TestBzzHandshakeLightNode
- [x] #1116 - pss deregister - TestProtocol, TestProxShortCircuit, TestSendRaw 
- [x] #1117 - storage.(*mockNetFetcher).Request()
- [x] #1118 - storage.testLDBStoreCollectGarbage()
- [x] #1154 - swarm.go
- [x] #1157 - swarm/pss TestProtocol
- [x] #1158 - pss/notify tests
- [x] #1160 - protocol.go Handshake
- [x] #1197 - swarm/network/stream

**Comment by frncmx** [comment]
The following import paths **contain data race**:
```
FAIL	github.com/ethereum/go-ethereum/swarm	68.952s
FAIL	github.com/ethereum/go-ethereum/swarm/network	14.767s
FAIL	github.com/ethereum/go-ethereum/swarm/network/simulation	10.920s
FAIL	github.com/ethereum/go-ethereum/swarm/network/stream	600.060s
FAIL	github.com/ethereum/go-ethereum/swarm/pss	34.629s
FAIL	github.com/ethereum/go-ethereum/swarm/storage	217.360s
```

Note: The tests for `storage` may get stuck and time out.

How to reproduce?
`go test -count 1 -race github.com/ethereum/go-ethereum/swarm...`
