### ISSUE TITLE
Kubernetes: Setup cluster-wide metrics collection

### ISSUE THREAD

**Issue by skylenet** [ethersphere/swarm#1127]
Moved from issue: ethereum/swarm-cluster#73

The current deploy stack was installed based on https://sysdig.com/blog/kubernetes-monitoring-prometheus-operator-part3/
```
git clone https://github.com/coreos/prometheus-operator.git
git clone https://github.com/mateobur/prometheus-monitoring-guide.git
kubectl create -f prometheus-operator/contrib/kube-prometheus/manifests/
```

## Todo:

- [x] Check if this is the best way to do it.
- [x] Add the installation of the metrics stack to the bootstrapping script.
- [x] Enable persistent storage for prometheus and check if it's also needed for grafana.
