### ISSUE TITLE
swarm/pss: Add docker node network simulation tests

### ISSUE THREAD

**Issue by nolash** [ethersphere/swarm#1421]
We need tests for larger network in cluster network scenarios. For this step, a test should bring up 1000 nodes, and verify relevant send and receive scenarios (various luminosity, sender distribution, message load ...)

## TASKS

- [ ] [execnode hello world with event monitoring](https://github.com/ethersphere/swarm/issues/1423)
- [ ] dockerify exec nodes
- [ ] add init and cleanup hooks to docker mode sim for auxiliary node controllers (kubernetes)
- [ ] implement simplest existing network test with docker nodes
