### ISSUE TITLE
Users can provide deployed SWAP contract

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/swarm#1548]
# Problem
Right now each time Swarm is started with swap flag, new SWAP cheque contract is deployed.

# Task
- [ ] Add a flag that allows users to provide a SWAP contract address
- [ ] Programatically validate the provided contract
- [ ] If incorrect, raise fatal error
- [ ] If no such flag is provided, the contract address should be retrieved from the nodes storage. If does not exist the contract should still be automatically deployed.

**Comment by mortelli** [comment]
See also #1599.

**Comment by mortelli** [comment]
for clarification purposes: could someone please document here (or there) the difference between this issue and #1599?

relevant PR: #1718
