### ISSUE TITLE
global pinning: phase 0

### ISSUE THREAD

**Issue by mortelli** [ethersphere/swarm#2153]
User story: [Global Pinning](https://github.com/ethersphere/user-stories/issues/74)

Issue for implementing **Phase 0** of global pinning.

## Tasks
- [x] implement trojan chunks.
- [x] refactor current `pss` package and API into `oldpss`.
- [x] add a new, minimal `pss` implementation with a `Send` method, which will create and store a trojan chunk for it to be sent through push sync.

## PRs
| # | title  | status  |
|---|---|---|
| #2146 | rename pss package to oldpss | **merged** |
| #2147 | add newpss incomplete | **closed** |
| #2148 | add trojan chunks | **merged** |
| #2149  | add pss without modification | **merged** |
| #2150 | add barebone new pss | **merged** |
| #2152 | remove pss package for global pinning | **merged** |

**Comment by mortelli** [comment]
completed
