### ISSUE TITLE
global pinning: phase 2

### ISSUE THREAD

**Issue by mortelli** [ethersphere/swarm#2161]
User story: [Global Pinning](https://github.com/ethersphere/user-stories/issues/74)

Issue for implementing **Phase 2** of global pinning.

## Tasks
- [x] implement a way to trigger the sending of the trojan chunk; this should happen after failing to download content which the node understands is globally pinned.
- [x] implement inheriting publisher info via the context.WithValue, construct and lookup the latest update of the pinners feed
- [x] implement a handler function to re-upload missing pinned content in the case of receiving such notification in the form of a trojan chunk.
- [x] implement monitoring of pss messages, this shows the status of the trojan chunk sent. 
- [x] add `Target` and `Targets` types to the trojan package as an improvement to readability and code clarity.
- [x] extend the `feed` package in order to properly test the `prod` package.

## PRs
| # | Title  | Status  |
|---|---|---|
| #2159 | add pss monitoring capabilities | **merged** |
| #2165 | repair globally pinned content | **merged** |
| #2166 | trigger trojan chunk sending | **merged** |
| #2175 | get publisher and query feed for chunk repair request | **merged** |
| #2178 | add Target and Targets types | **merged** |
| #2179  | add handler interface and testutils | **merged** |

**Comment by mortelli** [comment]
completed
