### ISSUE TITLE
sw3 contracts meta + timeline

### ISSUE THREAD

**Issue by zelig** [ethersphere/swarm#559]
after hackdays 2018-12-05 in Budapest:

Swap
- [ ] rewrite Swap tests so they don't affect each other (almost done already)
- [ ] moving cheque timeouts into cheques
- [ ] remove hardcoded timeouts in other places (e.g. hard depo decreases)
- [ ] define a format for the channel deposit allocation table
- [ ] implement the necessary change for soft deposits (CADT submission + refutation)
- [ ] bounties in Swap
- [ ] completing the Swap tests
- [ ] updating the docs (a bit outdated now)

Swear / Swindle
- [ ] rewrite witness interface and trial rules to work with role assignments
- [ ] rewrite Swindle with roles
- [ ] rewrite Swear contracts in a way so anyone can start cases and the commitment is presented in the first trial stage
- [ ] implement a sample trial for mailbox services to see if it makes sense

**Comment by zelig** [comment]
Obsolete tasklist created as a comment.

README (https://github.com/ethersphere/swap-swear-and-swindle/README.md)

Ralph Pichler
@ralph-pichler
May 16 10:46

here are some things that need experimentation if somebody wants to work on the contracts:

# witness:

 *   better witness interface
    *    often note_id is just some custom payload (see OracleTrial) (the remark = sha3(rules, sha3(payload data)) hack sucks)
    *  maybe keep using remark for swap-initiated swear deposits but forward the payload to the witnesses (not the note_id, if the witness really cares about the note it can still be included in the payload)

# swap:

* add custom timeouts for hard deposits (critical for swear integration)
*  mayble multiple timeouts for the same beneficiary (ideally with changes offchain?)
*  unify cheques and notes logic (implement index for notes, when does replacment make sense?)
 *  always pass fields as arguments to avoid contract storage

# swear:

* think about how this works with (potentially continous) payment on successful service
* clean up the messy commitment code (many fields are probably not needed)
* make the plaintiff related logic a bit more sane (right now anybody can start a trial for every commitment and potentially get the deposit)
*  support taking only part of the deposit in the offchain case (swap witness would have to receive payout amount)

# trials:

* create more test trials and witnesses for potential real world applications to see wether they can work with the witness / state machine concept

let me know if somebody wants to tackle something in this list so we avoid too much duplicate work
