### ISSUE TITLE
update roadmap and rename minor milestones

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#805]
TODO:
- [x] Edit https://github.com/ethereum/go-ethereum/wiki/swarm-roadmap and point to correct roadmap
- [x] Edit https://github.com/ethereum/go-ethereum/wiki/swarm-dev-progress and point to correct roadmap
- [x] Edit https://github.com/ethersphere/swarm/wiki/swarm-dev-progress and point to correct roadmap
- [x] Update Roadmap document at https://github.com/ethersphere/swarm/wiki/Roadmap
- [x] Edit https://github.com/ethersphere/go-ethereum/wiki/Git-Workflow and point to new Dev/Onboarding guide
- [x] Refactor and consolidate Onboarding Document and Developers' Guide - https://github.com/ethersphere/swarm/wiki/swarm and https://github.com/ethereum/go-ethereum/wiki/Developers'-Guide
- [x] Link new consolidated document from README.md and possibly from website? 

-----

I think our official Roadmap webpage, which I believe is https://github.com/ethersphere/swarm/wiki/Roadmap , as this is what the website is linking to, is quite confusing.

I think we should simplify it, and create a public Roadmap, which looks more like https://github.com/orgs/ethersphere/projects/5

I also think should come up with better names for POC 3.1, POC 3.2, etc. because this is currently messing up our patch releases. I'd like if possible to adhere to the https://semver.org/ semantics for releases. We have recently released POC 3 == Swarm 0.3.0, and I'd like us to be able to have stable incremental releases, similarly to Geth, every 2-3 weeks, with Swarm 0.3.1 being the next one. This will however NOT be the POC 3.1 displayed in the project board.

I am completely fine with having POC 4 == Swarm 0.4.0 , POC 5 == Swarm 0.5.0 , etc. - we can keep on releasing patch releases every 2-3 weeks, until we are ready with POC 4.

I think every patch release is also worthy of:
1. Reddit post
2. ethereum/swarm gitter /all announcement
3. Maybe Twitter post?

Note that this proposal goes against what has been communicated in https://blog.ethereum.org/2018/06/21/announcing-swarm-proof-of-concept-release-3/ . If we manage to agree within the team on how to proceed, I think we can easily communicate an updated Roadmap, via our website, Github, Reddit, etc.

Let me know what you think.

cc @zelig

**Comment by nonsense** [comment]
Some more discussions on this topic at: https://docs.google.com/document/d/1nRBFcJws0tPhA50C2XKMNx56H3Fnv82NedRp06G-yXE/edit

**Comment by cobordism** [comment]
*ahem*

https://github.com/ethereum/go-ethereum/wiki/swarm-roadmap
https://github.com/ethersphere/swarm/wiki/roadmap
https://github.com/ethereum/go-ethereum/wiki/swarm-dev-progress
https://github.com/ethersphere/swarm/wiki/swarm-dev-progress
https://github.com/orgs/ethersphere/projects/5
https://github.com/ethersphere/go-ethereum/wiki/Pss-roadmap

**Comment by nonsense** [comment]
@homotopycolimit @zelig I suggest we outright delete the following 3 pages, as I don't see them bring any value at present:

https://github.com/ethereum/go-ethereum/wiki/swarm-roadmap
https://github.com/ethereum/go-ethereum/wiki/swarm-dev-progress
https://github.com/ethersphere/swarm/wiki/swarm-dev-progress

The development progress and the Roadmap should be communicated at one place to external people, and the most up-to-date page (which we should refactor) is: https://github.com/ethersphere/swarm/wiki/Roadmap

What do you think?

**Comment by nonsense** [comment]
This ticket is now solely about updating the Roadmap on all outdated wiki pages and on the website.

**Comment by cobordism** [comment]
- [ ] Come up with named(!) milestones and add them to roadmap

**Comment by nonsense** [comment]
Not sure why we are closing this one.

**Comment by acud** [comment]
we have already reached an agreement upon the fact that the roadmap will be communicated through the swarm website if you can remember.
this issue does not help us keep track of this since the roadmap on our git board is already managed and somewhat in sync. hence the main task is to do the website part and therefore an issue has been opened on `swarm-home`
