### ISSUE TITLE
Let's update the Swarm Manifest

### ISSUE THREAD

**Issue by cobordism** [ethersphere/swarm#878]
We've long talked about updating the Swarm Manifest data structure to allow for more advanced use-cases from path based routing to query string management.
This Issue collects all the changes we discussed over time.

----
## Default entry is a path not a hash

- [x] Default manifest entry should not be a hash associated to the empty path, but a relative path associated with an explicit 'default' marker. 

Thus a manifest in which the default is index.html should no longer have the empty path `''` associated with a `hash` that happens to be the same hash as that associated with `index.html` but rather it should have a `default` entry which maps to `index.html`.  While we might sometimes need more bzz manifest lookups, we gain simplicity in housekeeping.

Related issues and discussions 
https://github.com/ethersphere/go-ethereum/issues/162 https://gist.github.com/homotopycolimit/7b70436326535ef19028f836680a1f3c
https://github.com/ethersphere/go-ethereum/issues/178#issuecomment-354015522
https://gist.github.com/homotopycolimit/a83ad855a03190463738e93fcf6aa339
https://github.com/ethersphere/go-ethereum/pull/824

- [x] prepare for easy updating of current manifests to this new type
- [x] deprecate the current empty-path-as-default manifests.

----
## Manifest can define its own routing / path matching

- [ ] Prepare for different "types" of manifest. 
- [ ] Define the "directory" (default) type

We discussed having a 'directory' type manifest which adheres to specific rules (eg. any entry ending in `/` has to be of type bzz-manifest+json ) and which can always be FUSE mountable. We discussed having other manifests which explicitly state what to do with over / undermatched paths. For example if a manifest contains only `'index.html` what should be done with `index.h` or with `index.html?a=b`? If we want to enable apps that use path based routing, then manifests need to be more flexible in how they handle bzz queries - perhaps even allowing regular expressions?
We can also imagine allowing manifests to specify HTTP 301 redirect entries which would map to symlinks in fuse. We need discussion on this.
 
See also https://github.com/ethereum/go-ethereum/issues/14349 (as well as the discussions linked above)

- [ ] Create github issue discussions for the specific manifest types we might want to implement beyond the 'standard' directory type we are using now. RegExp, Overmatch, undermatch, ignore?querystring... (I'd like input from @lmars and @nagydani and others here)

----

## prepare cli commands to work with new manifest

- [ ] `swarm --recursive up` should generate directory manifest types
- [ ] `swarm fs` should warn when attempting to mount non directory manifest types (or even fail). 
- [ ] `swarm up file` should generate a manifest with a named file and a default entry referring to the file as opposed to an unamed default file only.

----

Related to this question is that of cleaning up the bzz-list output
https://github.com/ethersphere/go-ethereum/issues/726
https://github.com/ethersphere/go-ethereum/issues/156

----
## Docs

- [ ] Add documentation for the above changes to swarm-guide as needed.

**Comment by cobordism** [comment]
What is missing of course right now is any tooling to manipulate manifests.
And you already saw that having the same hash twice (once for index.html and once for `''`) creates issues for the tools, the encryption cased a problem too. 
So while I agree that 'users' are not meant to manipulate manifests by hand, Swarm webmasters are expected to manipulate manifests through not-yet-written tools.

Having the path reference instead of the hash is only slower if `index.html` (or whatever the default is) isn't listed in the same manifest but within some submanifest... and it will never be slower than calling `/index.html` directly.
The question is, is the little performance increase worth the extra complexity in the tooling?

**Comment by cobordism** [comment]
- [ ] better concrete manifest entry type that will allow us to describe metadata entries better.
for example 

for example for ACTs

**Comment by acud** [comment]
In my endeavor to try and crunch the information a bit more, I can give further input regarding the issues above, and add more on top:

------

### no empty directory representation:

As of now, except for manually tampering and editing a manifest, there exists no way in swarm to represent an empty directory in a manifest. That is since directory manifests and trie split entries have no distinctions. This is due to the fact that directories have no formal representation in swarm.
Solution: see trailing slash below

---------

### default entry behaviour

Default entry path has to be manually specified in the CLI. This should be mended and we should at least try to identify a default `index.html`, or an entry point specified within a `package.json` when uploading with `swarm up` (with a possibility to turn this off). So the default behaviour would auto-detect, a `--defaultpath` would override, and `--nodefaultpath` would leave it empty
_Open question - should we allow subpaths as default entry? e.g. that the path is ‘./src/index.html’?_

-------

### default entry is a manifest entry

This should not be the case, and it should be specified on the manifest metadata level as this introduces redundant data into the manifest entries data structure.

--------

### inconsistent naming conventions in the manifest definition

`contentType` as opposed to `mod_time`

---------

### allowing redirections and symlink alignment

Can be resolved with adding a symlink file type as @lmars suggested in https://github.com/ethereum/go-ethereum/issues/14345#issuecomment-294964250

--------

### Tasks:

1. Manifest tooling: 
- [x] Auto detect default entry - index.html/package.json entry point (783)
- [x] Allow users to disable default entry detection 
- [ ] Create flag to follow symlinks (solves 3601)
- [x] Go through manifest error messages (solves 726)
2. Manifest data structure:
- [x] Add default entry as a path, not a hash, `next to` (as opposed to `inside of`) `entries`
- [ ] Add manifest type annotation - trie split or a directory
3. Traversal behaviour - path match/undermatch/overmatch:
- [x] Manifest without default entry should return bzz-list on http get - this should be possible to disable on the manifest level - similar as with `autoindex` directive on nginx or `mod_autoindex`/`Indexes` on httpd

**NOTE: Unix FS allows everything except `NULL` or `/` to be inputted as a filename**
- This is problematic when choosing to undermatch on `?` or other characters
- This can be cumbersome when allowing manifests to define their own matching rules
**Recommendation:** return an element only if it is directly found - do not allow overmatch or undermatch


---------


### Trailing slash problem:
1. Current structure functions both as an indice and as an filesystem representation:
- Both are designed to solve different problems
- For most cases, the first is auxiliary to the latter
2. In current design we break (break = create a new trie fork) 
- on a common prefix (has more than one child by definition)
- ..and that’s it
3. In the current design a slash is irrelevant - only the number of children
- Assumptions:	
- This is a search trie design consideration, not a file system representation consideration
- A file system representation cares about slashes (in fact, *nix filesystems care for slashes only)
- A file system representation does not care about the number of children inodes as a precondition for a directory inode’s creation
- The network complexity on lookups benefits with this design in the case that a directory contains a large number of flat subdirectories that contain only one element => no trie forks due to slashes


### Possible solutions:
1. Adopt Ext4 (or similar) structure - where:
1.1. Each directory would be a manifest
1.2. For each directory we keep an indice stored inside the manifest, side by side by the entries. This can also allow different implementations of the search tries to be included in different types of manifests (or according to runtime optimisations). 
1.3. The indice could be stored in the json as binary in base64 encoding
1.4. The indice node will contain an inode or path which will be mapped to the relevant manifest entry through a hashmap/dictionary
1.5 Optional: store dot + dotdot entries to allow bidirectional manifest traversal?
in this case, we end up with something like:
```
{
   "entries":[
      {
         "inode":1,
         "path":"folder1", //might not be necessary 
         "type":"application/bzz-manifest+json",
         "hash":"<hash>"
      },
      {
         "inode":2,
         "path":"file1.txt", //might not be necessary
         "type":"text/plain",
         "hash":"<hash>"
      }
   ],
   "indice":"c29tZXJhbmRvbWluZGljZXRleHRnb2VzaGVyZQ==",
   "type": "directory",
   "default":2 //inode; faster lookup?
}
```

2. Find a hybrid implementation between current implementation and Ext4 model where:
2.1. We insert artificial directory entries into manifests when traversing filesystem trees upon manifest creation; with the drawback that: 
2.2. this structure cannot be enforced by definition - it’s an implementation detail and it is up to the client/uploader if to conform with this structure, which could in turn lead to inconsistencies for the network to keep up its promise

-------

### references:
https://github.com/ethersphere/go-ethereum/issues/156 - manifests without a default path should default to list request
https://github.com/ethersphere/go-ethereum/issues/878 - this sip - default entry is a path not a hash, manifest can define its own routing / path matching, prepare cli commands to work with new manifest
https://github.com/ethersphere/go-ethereum/issues/162 - default entry
https://github.com/ethersphere/go-ethereum/issues/178 - trailing slash problem [1]
https://github.com/ethersphere/go-ethereum/issues/726 - error msg refining
https://github.com/ethersphere/go-ethereum/issues/783 - default entry - auto detect on index.html
https://github.com/ethereum/go-ethereum/issues/14349 - directory manifest type [1]
https://github.com/ethereum/go-ethereum/issues/14345 - support http redirect
https://github.com/ethereum/go-ethereum/issues/3601 - swarm recursive up fails on symlinks - resolved?
